/*
 * Copyright (c) 1991-2026 Université catholique de Louvain
 *
 * <p>Center for Operations Research and Econometrics (CORE)
 *
 * <p>http://www.uclouvain.be
 *
 * <p>This file is intended as a user modal split plugin for Nodus.
 *
 * <p>Nodus is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

import edu.uclouvain.core.nodus.NodusProject;
import edu.uclouvain.core.nodus.compute.assign.AssignmentParameters;
import edu.uclouvain.core.nodus.compute.assign.modalsplit.ModalSplitMethod;
import edu.uclouvain.core.nodus.compute.assign.modalsplit.Path;
import edu.uclouvain.core.nodus.compute.assign.modalsplit.PathsForMode;
import edu.uclouvain.core.nodus.compute.assign.workers.PathWeights;
import edu.uclouvain.core.nodus.compute.od.ODCell;
import edu.uclouvain.core.nodus.database.JDBCUtils;
import edu.uclouvain.core.nodus.tools.console.NodusConsole;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Iterator;
import java.util.List;
import java.util.Properties;
import java.util.regex.Pattern;

/**
 * Calibrated freight modal-choice model for road, inland waterways and rail.
 *
 * <p>This plugin implements the model estimated by
 * modal_choice_biogeme_sequential_framework_calibrated_dbparams.py. The model is expressed relative
 * to road:
 *
 * <pre>
 * V_road = 0
 *
 * V_iww = ASC_IWW[g]
 *       + B_COST_IWW * (ln(cost_iww / cost_road) - center_cost_iww)
 *       + B_MOVE_IWW * (ln(moving_time_iww / moving_time_road) - center_time_iww)
 *       + distance_spline_iww
 *       + calibration_iww
 *
 * V_rail = ASC_RAIL[g]
 *        + optional B_COST_RAIL * (ln(cost_rail / cost_road) - center_cost_rail)
 *        + B_MOVE_RAIL * (ln(moving_time_rail / moving_time_road) - center_time_rail)
 *        + distance_spline_rail
 *        + B_RAIL_IWW_AVAILABLE * I(IWW available)
 *        + calibration_rail
 * </pre>
 *
 * <p>Road is mode 1, inland waterways are mode 2 and rail is mode 3. Road is the reference mode.
 *
 * <p>All model-defining parameters are read from a database table generated by the Python
 * estimation script. The .costs file is intentionally kept minimal. It should contain only the
 * name of the parameter table and, optionally, purely operational plugin options such as path
 * spreading.
 *
 * <p>Typical .costs fragment:
 *
 * <pre>
 * @paramTable=modal_choice_params_model1
 * @MC.ApplyCalibration=true          # optional; defaults to the database-table setting
 * @MC.SpreadPathsByInverseCost=true  # optional operational setting
 * </pre>
 *
 * <p>The table must contain at least:
 *
 * <pre>
 * param_key    VARCHAR
 * param_value  TEXT or VARCHAR
 * </pre>
 *
 * <p>The plugin does not use model-defining values from the .costs file. This avoids accidentally
 * applying a different model from the one estimated in Python. For example, options such as
 * {@code @MC.IncludeRailCost}, {@code @MC.CalibrationLevel}, and
 * {@code @MC.DistanceThresholdsKm} must come from the database table. The current runtime
 * options accepted from the .costs file are:
 *
 * <ul>
 *   <li>{@code @MC.SpreadPathsByInverseCost}, which controls how a mode's market share is
 *       distributed over its available paths;
 *   <li>{@code @MC.ApplyCalibration}, which may disable the base-year calibration layer at runtime
 *       when calibration constants exist in the database table. It may not activate calibration if
 *       the table was generated by a Python run without calibration.
 * </ul>
 *
 * <p>Important: the estimated model uses moving times, not total transit times. This plugin therefore
 * uses {@code c.mvDuration / 3600.0} as the time input, as requested. The division by 3600 converts
 * seconds to hours.
 *
 * <p>Once the modal split is computed, the quantity assigned to a mode is spread over the available
 * paths of that mode proportionally to inverse path cost, following the convention used in the
 * LogAccessibility example plugin.
 */
public class CalibratedODModalChoice extends ModalSplitMethod {

  private static final int MODE_ROAD = 1;
  private static final int MODE_IWW = 2;
  private static final int MODE_RAIL = 3;

  private static final double EPS = 1.0e-12;
  private static final double UNAVAILABLE_UTILITY = -1.0e6;
  private static final Pattern SAFE_TABLE_NAME = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");

  private NodusProject nodusProject;

  // Properties read from the Nodus .costs file. In the simplified production
  // design, this container is used only to find @paramTable and to read
  // operational options that do not change the estimated modal-choice model.
  private Properties costFunctions;

  // Properties loaded from the database parameter table. All behavioral
  // coefficients, centering constants, distance settings, calibration settings,
  // and calibration constants must be read from this container.
  private Properties modelParameters = new Properties();

  private String paramTable;
  private boolean parametersAvailable = true;

  private boolean includeRailCost;
  private boolean useCalibration;
  private boolean spreadPathsByInverseCost;
  private String calibrationLevel;

  private double distanceScaleKm;
  private double[] thresholdsKm;

  private double ascIww;
  private double ascRail;
  private double bCostIww;
  private double bMoveIww;
  private double bCostRail;
  private double bMoveRail;
  private double bRailIwwAvailable;

  private double centerCostIww;
  private double centerMoveIww;
  private double centerCostRail;
  private double centerMoveRail;

  private int segmentCount;
  private double[] bDistIww;
  private double[] bDistRail;
  private double[] centerDsegIww;
  private double[] centerDsegRail;

  /**
   * Default constructor. Called by Nodus when the plugin is loaded.
   *
   * @param nodusProject Nodus project associated with this modal split method.
   */
  public CalibratedODModalChoice(NodusProject nodusProject) {
    super(nodusProject);
  }

  /**
   * Initialize assignment-level settings.
   *
   * <p>The simplified production policy is deliberately strict:
   *
   * <ul>
   *   <li>The {@code .costs} file must provide {@code @paramTable}.
   *   <li>All model-defining values are read from that database table.
   *   <li>The {@code .costs} file is allowed to provide only runtime options that do not change
   *       the estimated coefficients: currently {@code @MC.SpreadPathsByInverseCost} and
   *       {@code @MC.ApplyCalibration}.
   * </ul>
   *
   * <p>This avoids inconsistencies such as applying a calibration level or a rail-cost option that
   * does not match the coefficients stored in the parameter table.
   *
   * @param assignmentParameters Assignment parameters.
   */
  @Override
  public void initialize(AssignmentParameters assignmentParameters) {
    super.initialize(assignmentParameters);

    nodusProject = getNodusProject();
    costFunctions = getAssignmentParameters().getCostFunctions();

    // @paramTable is the only model-related value that must be placed in the
    // .costs file. It tells the plugin where the estimated model is stored.
    paramTable = getCostString("@paramTable", getCostString("@MC.ParamTable", "")).trim();
    if (paramTable.isEmpty()) {
      parametersAvailable = false;
      System.err.println(
          "CalibratedODModalChoice: missing @paramTable. "
              + "All model parameters must be stored in a database table.");
      return;
    }

    parametersAvailable = loadParameterTable(paramTable);
    if (!parametersAvailable) {
      return;
    }

    try {
      // Model-defining options are read from the database table only.
      includeRailCost = getModelBooleanRequired("@MC.IncludeRailCost");
      boolean tableHasCalibration = getModelBooleanRequired("@MC.UseCalibration");
      calibrationLevel = getModelStringRequired("@MC.CalibrationLevel").toLowerCase();
      if (!isKnownCalibrationLevel(calibrationLevel)) {
        throw new IllegalStateException(
            "unsupported @MC.CalibrationLevel in parameter table "
                + paramTable
                + ": "
                + calibrationLevel);
      }
      distanceScaleKm = getModelDoubleRequired("@MC.DistanceScaleKm");
      thresholdsKm = parseThresholds(getModelStringRequired("@MC.DistanceThresholdsKm"));

      // @MC.ApplyCalibration is a runtime switch. It may be placed in the .costs file to
      // temporarily run the behavioral model without the base-year calibration layer.
      // It cannot activate calibration when the database table was generated from a Python
      // run without calibration constants.
      boolean applyCalibration = getCostBoolean("@MC.ApplyCalibration", tableHasCalibration);
      if (applyCalibration && !tableHasCalibration) {
        throw new IllegalStateException(
            "@MC.ApplyCalibration=true was requested in the .costs file, but parameter table "
                + paramTable
                + " was generated without calibration constants (@MC.UseCalibration=false).");
      }
      useCalibration = tableHasCalibration && applyCalibration;

      if (useCalibration && calibrationLevel.equals("none")) {
        throw new IllegalStateException(
            "@MC.UseCalibration=true in parameter table "
                + paramTable
                + " but @MC.CalibrationLevel=none. The table is internally inconsistent.");
      }

      // This is an operational path-allocation option, not a modal-choice model
      // parameter. It may therefore be kept in the .costs file.
      spreadPathsByInverseCost = getCostBoolean("@MC.SpreadPathsByInverseCost", true);
    } catch (IllegalStateException ex) {
      parametersAvailable = false;
      System.err.println("CalibratedODModalChoice: " + ex.getMessage());
    }
  }

  /**
   * Load modal-choice parameters from the database table named by {@code @paramTable}.
   *
   * <p>The rows are stored in {@link #modelParameters}, not merged into the .costs property set. This
   * separation is intentional: it guarantees that estimated model settings cannot be overridden by
   * values left in the .costs file.
   */
  private boolean loadParameterTable(String tableName) {
    if (!SAFE_TABLE_NAME.matcher(tableName).matches()) {
      System.err.println(
          "CalibratedODModalChoice: invalid @paramTable name '" + tableName + "'.");
      return false;
    }

    if (!JDBCUtils.tableExists(tableName)) {
      System.err.println(
          "CalibratedODModalChoice: parameter table " + tableName + " not found in database.");
      return false;
    }

    int count = 0;
    modelParameters.clear();
    try {
      Connection con = nodusProject.getMainJDBCConnection();
      Statement stmt = con.createStatement();
      ResultSet rs = stmt.executeQuery("select param_key, param_value from " + tableName);
      while (rs.next()) {
        String key = rs.getString(1);
        String value = rs.getString(2);
        if (key != null && value != null) {
          modelParameters.setProperty(key.trim(), value.trim());
          count++;
        }
      }
      rs.close();
      stmt.close();
    } catch (Exception ex) {
      new NodusConsole();
      System.err.println("CalibratedODModalChoice: error while reading " + tableName + ": " + ex);
      return false;
    }

    System.out.println(
        "CalibratedODModalChoice: loaded " + count + " parameters from table " + tableName + ".");
    return count > 0;
  }

  /**
   * Initialize group-specific parameters.
   *
   * <p>Nodus calls this method when it starts assigning a commodity group. The group-specific ASCs
   * and all behavioral coefficients are read from the database parameter table. Missing model
   * parameters are treated as configuration errors. Calibration constants are the only exception: a
   * missing calibration key means a zero correction for that cell.
   *
   * @param currentGroup Current commodity group.
   */
  @Override
  public void initializeGroup(int currentGroup) {
    super.initializeGroup(currentGroup);

    if (!parametersAvailable) {
      return;
    }

    try {
      ascIww = getModelDoubleRequired("mc.asc.iww." + currentGroup);
      ascRail = getModelDoubleRequired("mc.asc.rail." + currentGroup);

      bCostIww = getModelDoubleRequired("mc.b_cost_iww");
      bMoveIww = getModelDoubleRequired("mc.b_move_iww");
      bCostRail = includeRailCost ? getModelDoubleRequired("mc.b_cost_rail") : 0.0;
      bMoveRail = getModelDoubleRequired("mc.b_move_rail");
      bRailIwwAvailable = getModelDoubleRequired("mc.b_rail_iww_available");

      centerCostIww = getModelDoubleRequired("mc.center.ln_cost_ratio_iww");
      centerMoveIww = getModelDoubleRequired("mc.center.ln_move_ratio_iww");
      centerCostRail = getModelDoubleRequired("mc.center.ln_cost_ratio_rail");
      centerMoveRail = getModelDoubleRequired("mc.center.ln_move_ratio_rail");

      segmentCount = (int) Math.round(getModelDoubleRequired("mc.distance.segment.count"));
      if (segmentCount < 1) {
        throw new IllegalStateException("mc.distance.segment.count must be >= 1.");
      }

      bDistIww = new double[segmentCount + 1];
      bDistRail = new double[segmentCount + 1];
      centerDsegIww = new double[segmentCount + 1];
      centerDsegRail = new double[segmentCount + 1];

      for (int i = 1; i <= segmentCount; i++) {
        bDistIww[i] = getModelDoubleRequired("mc.b_dist_iww." + i);
        bDistRail[i] = getModelDoubleRequired("mc.b_dist_rail." + i);
        centerDsegIww[i] = getModelDoubleRequired("mc.center.dseg_iww." + i);
        centerDsegRail[i] = getModelDoubleRequired("mc.center.dseg_rail." + i);
      }
    } catch (IllegalStateException ex) {
      parametersAvailable = false;
      System.err.println("CalibratedODModalChoice: " + ex.getMessage());
    }
  }

  @Override
  public String getPrettyName() {
    return "Calibrated OD modal choice";
  }

  @Override
  public String getName() {
    return "calibrated-od-mnl";
  }

  /**
   * Compute the modal split for one OD cell.
   *
   * @param odCell OD cell for which the modal split is computed.
   * @param pathsLists List of mode-specific path lists.
   * @return True if the split was computed.
   */
  @Override
  public boolean split(ODCell odCell, List<PathsForMode> pathsLists) {
    if (!parametersAvailable) {
      return false;
    }

    PathsForMode roadPaths = findPathsForMode(pathsLists, MODE_ROAD);
    PathsForMode iwwPaths = findPathsForMode(pathsLists, MODE_IWW);
    PathsForMode railPaths = findPathsForMode(pathsLists, MODE_RAIL);

    if (roadPaths == null) {
      System.err.println("CalibratedODModalChoice: road alternative not found for " + odCell);
      return false;
    }

    double roadCost = positiveCost(roadPaths.cheapestPathWeights);
    double roadTime = positiveMovingTimeHours(roadPaths.cheapestPathWeights);
    double roadDistanceKm = positiveLengthKm(roadPaths.cheapestPathWeights);

    double utilityRoad = 0.0;
    double utilityIww = UNAVAILABLE_UTILITY;
    double utilityRail = UNAVAILABLE_UTILITY;

    if (iwwPaths != null) {
      utilityIww = computeIwwUtility(odCell, iwwPaths, roadCost, roadTime, roadDistanceKm);
    }

    if (railPaths != null) {
      utilityRail = computeRailUtility(
          odCell, railPaths, roadCost, roadTime, roadDistanceKm, iwwPaths != null);
    }

    double maxUtility = Math.max(utilityRoad, Math.max(utilityIww, utilityRail));
    double denom = 0.0;
    double expRoad = Math.exp(utilityRoad - maxUtility);
    denom += expRoad;

    double expIww = 0.0;
    if (iwwPaths != null) {
      expIww = Math.exp(utilityIww - maxUtility);
      denom += expIww;
    }

    double expRail = 0.0;
    if (railPaths != null) {
      expRail = Math.exp(utilityRail - maxUtility);
      denom += expRail;
    }

    roadPaths.utility = utilityRoad;
    roadPaths.marketShare = expRoad / denom;

    if (iwwPaths != null) {
      iwwPaths.utility = utilityIww;
      iwwPaths.marketShare = expIww / denom;
    }

    if (railPaths != null) {
      railPaths.utility = utilityRail;
      railPaths.marketShare = expRail / denom;
    }

    if (spreadPathsByInverseCost) {
      spreadOverPaths(pathsLists);
    } else {
      assignAllToCheapestPath(pathsLists);
    }
    return true;
  }

  private double computeIwwUtility(
      ODCell odCell,
      PathsForMode iwwPaths,
      double roadCost,
      double roadTime,
      double roadDistanceKm) {
    PathWeights weights = iwwPaths.cheapestPathWeights;
    double cost = positiveCost(weights);
    double time = positiveMovingTimeHours(weights);

    double centeredCost = Math.log(cost / roadCost) - centerCostIww;
    double centeredTime = Math.log(time / roadTime) - centerMoveIww;

    double utility = ascIww + bCostIww * centeredCost + bMoveIww * centeredTime;
    utility += distanceSplineUtility(roadDistanceKm, bDistIww, centerDsegIww);
    utility += getCalibrationConstant("iww", odCell, roadDistanceKm, true);
    return utility;
  }

  private double computeRailUtility(
      ODCell odCell,
      PathsForMode railPaths,
      double roadCost,
      double roadTime,
      double roadDistanceKm,
      boolean iwwAvailable) {
    PathWeights weights = railPaths.cheapestPathWeights;
    double cost = positiveCost(weights);
    double time = positiveMovingTimeHours(weights);

    double centeredCost = Math.log(cost / roadCost) - centerCostRail;
    double centeredTime = Math.log(time / roadTime) - centerMoveRail;

    double utility = ascRail + bCostRail * centeredCost + bMoveRail * centeredTime;
    utility += distanceSplineUtility(roadDistanceKm, bDistRail, centerDsegRail);
    utility += bRailIwwAvailable * (iwwAvailable ? 1.0 : 0.0);
    utility += getCalibrationConstant("rail", odCell, roadDistanceKm, iwwAvailable);
    return utility;
  }

  /**
   * Compute distance spline contribution using the same piecewise linear segments as in Python. The
   * distance is first divided by @MC.DistanceScaleKm, usually 100 km.
   */
  private double distanceSplineUtility(double roadDistanceKm, double[] betas, double[] centers) {
    double x = roadDistanceKm / Math.max(distanceScaleKm, EPS);
    double[] segments = computeSegments(x);
    double utility = 0.0;
    for (int i = 1; i <= segmentCount; i++) {
      utility += betas[i] * (segments[i] - centers[i]);
    }
    return utility;
  }

  /** Compute raw spline segments in scaled distance units. */
  private double[] computeSegments(double scaledDistance) {
    double[] segments = new double[segmentCount + 1];
    double lower = 0.0;
    for (int i = 1; i <= segmentCount; i++) {
      double upper;
      if (i <= thresholdsKm.length) {
        upper = thresholdsKm[i - 1] / Math.max(distanceScaleKm, EPS);
        segments[i] = Math.max(0.0, Math.min(scaledDistance - lower, upper - lower));
        lower = upper;
      } else {
        segments[i] = Math.max(0.0, scaledDistance - lower);
      }
    }
    return segments;
  }

  /** Read a calibration constant for the current OD cell. Returns zero if no matching key exists. */
  private double getCalibrationConstant(
      String modeName, ODCell odCell, double roadDistanceKm, boolean iwwAvailable) {
    if (!useCalibration || calibrationLevel.equals("none")) {
      return 0.0;
    }

    String keyBase = "mc.cal." + modeName;
    int origin = odCell.getOriginNodeId();
    int destination = odCell.getDestinationNodeId();
    int group = odCell.getGroup();

    if (calibrationLevel.equals("mode")) {
      return getModelDoubleOptional(keyBase, 0.0);
    }
    if (calibrationLevel.equals("mode_group")) {
      return getModelDoubleOptional(keyBase + "." + group, 0.0);
    }
    if (calibrationLevel.equals("mode_distance")) {
      return getModelDoubleOptional(keyBase + "." + distanceBandKey(roadDistanceKm), 0.0);
    }
    if (calibrationLevel.equals("mode_group_distance")) {
      return getModelDoubleOptional(keyBase + "." + group + "." + distanceBandKey(roadDistanceKm), 0.0);
    }
    if (calibrationLevel.equals("mode_iww_availability")) {
      return getModelDoubleOptional(keyBase + "." + (iwwAvailable ? "1" : "0"), 0.0);
    }
    if (calibrationLevel.equals("mode_group_iww_availability")) {
      return getModelDoubleOptional(keyBase + "." + group + "." + (iwwAvailable ? "1" : "0"), 0.0);
    }
    if (calibrationLevel.equals("mode_od")) {
      return getModelDoubleOptional(keyBase + "." + origin + "." + destination, 0.0);
    }
    if (calibrationLevel.equals("mode_od_group")) {
      return getModelDoubleOptional(keyBase + "." + origin + "." + destination + "." + group, 0.0);
    }

    // This should never happen because initialize(...) validates the calibration level.
    System.err.println(
        "CalibratedODModalChoice: unsupported calibration level " + calibrationLevel);
    return 0.0;
  }

  /**
   * Distance-band key compatible with the Python database export. The Python script creates
   * distance-band labels from the same @MC.DistanceThresholdsKm values stored in the parameter
   * table. With thresholds 150,300 the labels are 0-150, 150-300, 300+ and the keys requested here
   * are 0_150, 150_300 and 300plus.
   */
  private String distanceBandKey(double roadDistanceKm) {
    double lower = 0.0;
    for (double upper : thresholdsKm) {
      if (roadDistanceKm < upper) {
        return formatBandBoundary(lower) + "_" + formatBandBoundary(upper);
      }
      lower = upper;
    }
    return formatBandBoundary(lower) + "plus";
  }

  private String formatBandBoundary(double value) {
    if (Math.abs(value - Math.rint(value)) < 1.0e-9) {
      return Integer.toString((int) Math.rint(value));
    }
    return Double.toString(value).replace('.', 'p');
  }

  private PathsForMode findPathsForMode(List<PathsForMode> pathsLists, int mode) {
    Iterator<PathsForMode> it = pathsLists.iterator();
    while (it.hasNext()) {
      PathsForMode modalPaths = it.next();
      if (modalPaths.loadingMode == mode) {
        return modalPaths;
      }
    }
    return null;
  }

  /** Spread each mode's market share over its paths proportionally to inverse path cost. */
  private void spreadOverPaths(List<PathsForMode> pathsLists) {
    Iterator<PathsForMode> plIt = pathsLists.iterator();
    while (plIt.hasNext()) {
      PathsForMode modalPaths = plIt.next();
      double denominator = 0.0;
      Iterator<Path> it = modalPaths.pathList.iterator();
      while (it.hasNext()) {
        Path path = it.next();
        denominator += 1.0 / Math.max(path.weights.getCost(), EPS);
      }

      it = modalPaths.pathList.iterator();
      while (it.hasNext()) {
        Path path = it.next();
        path.marketShare =
            ((1.0 / Math.max(path.weights.getCost(), EPS)) / denominator)
                * modalPaths.marketShare;
      }
    }
  }

  /** Assign all of a mode's market share to its cheapest path. */
  private void assignAllToCheapestPath(List<PathsForMode> pathsLists) {
    Iterator<PathsForMode> plIt = pathsLists.iterator();
    while (plIt.hasNext()) {
      PathsForMode modalPaths = plIt.next();
      Iterator<Path> it = modalPaths.pathList.iterator();
      while (it.hasNext()) {
        Path path = it.next();
        path.marketShare = 0.0;
      }
      if (!modalPaths.pathList.isEmpty()) {
        modalPaths.pathList.get(0).marketShare = modalPaths.marketShare;
      }
    }
  }

  private double positiveCost(PathWeights weights) {
    return Math.max(weights.getCost(), EPS);
  }

  /** Moving duration in hours. Nodus stores mvDuration in seconds. */
  private double positiveMovingTimeHours(PathWeights weights) {
    return Math.max(weights.mvDuration / 3600.0, EPS);
  }

  private double positiveLengthKm(PathWeights weights) {
    return Math.max(weights.getLength(), EPS);
  }

  /** Read a string option from the .costs file only. */
  private String getCostString(String key, String defaultValue) {
    String value = costFunctions.getProperty(key);
    if (value == null) {
      return defaultValue;
    }
    return value.trim();
  }

  /** Read an operational boolean option from the .costs file only. */
  private boolean getCostBoolean(String key, boolean defaultValue) {
    String value = costFunctions.getProperty(key);
    if (value == null) {
      return defaultValue;
    }
    value = value.trim().toLowerCase();
    return value.equals("true") || value.equals("yes") || value.equals("1");
  }

  /** Return true if a key exists in the database parameter table. */
  private boolean hasModelParameter(String key) {
    return modelParameters.getProperty(key) != null;
  }

  /** Read a required string parameter from the database parameter table. */
  private String getModelStringRequired(String key) {
    String value = modelParameters.getProperty(key);
    if (value == null) {
      throw new IllegalStateException("required model parameter missing from table "
          + paramTable + ": " + key);
    }
    return value.trim();
  }

  /** Read a required boolean parameter from the database parameter table. */
  private boolean getModelBooleanRequired(String key) {
    String value = getModelStringRequired(key).toLowerCase();
    if (value.equals("true") || value.equals("yes") || value.equals("1")) {
      return true;
    }
    if (value.equals("false") || value.equals("no") || value.equals("0")) {
      return false;
    }
    throw new IllegalStateException("invalid boolean model parameter in table "
        + paramTable + ": " + key + " = " + value);
  }

  /** Read a required numeric parameter from the database parameter table. */
  private double getModelDoubleRequired(String key) {
    String value = getModelStringRequired(key);
    try {
      return Double.parseDouble(value);
    } catch (NumberFormatException e) {
      throw new IllegalStateException("invalid numeric model parameter in table "
          + paramTable + ": " + key + " = " + value);
    }
  }

  /**
   * Read an optional numeric parameter from the database parameter table.
   *
   * <p>This is used for calibration constants only. Missing calibration constants are interpreted as
   * zero so that the database does not need to store rows for all zero corrections.
   */
  private double getModelDoubleOptional(String key, double defaultValue) {
    if (!hasModelParameter(key)) {
      return defaultValue;
    }
    String value = modelParameters.getProperty(key).trim();
    try {
      return Double.parseDouble(value);
    } catch (NumberFormatException e) {
      System.err.println("CalibratedODModalChoice: invalid optional numeric model parameter in table "
          + paramTable + ": " + key + " = " + value);
      return defaultValue;
    }
  }

  /** Return true if the calibration level is one of the levels produced by the Python script. */
  private boolean isKnownCalibrationLevel(String level) {
    return level.equals("none")
        || level.equals("mode")
        || level.equals("mode_group")
        || level.equals("mode_distance")
        || level.equals("mode_group_distance")
        || level.equals("mode_iww_availability")
        || level.equals("mode_group_iww_availability")
        || level.equals("mode_od")
        || level.equals("mode_od_group");
  }

  /** Parse comma-separated distance thresholds in kilometres, for example "150,300". */
  private double[] parseThresholds(String csv) {
    String[] parts = csv.split(",");
    if (parts.length == 0) {
      throw new IllegalStateException(
          "empty @MC.DistanceThresholdsKm value in table " + paramTable + ": " + csv);
    }

    double[] values = new double[parts.length];
    for (int i = 0; i < parts.length; i++) {
      try {
        values[i] = Double.parseDouble(parts[i].trim());
      } catch (NumberFormatException e) {
        throw new IllegalStateException(
            "invalid @MC.DistanceThresholdsKm value in table " + paramTable + ": " + csv);
      }

      if (values[i] <= 0.0) {
        throw new IllegalStateException(
            "@MC.DistanceThresholdsKm must contain strictly positive values in table "
                + paramTable
                + ": "
                + csv);
      }
      if (i > 0 && values[i] <= values[i - 1]) {
        throw new IllegalStateException(
            "@MC.DistanceThresholdsKm must be strictly increasing in table "
                + paramTable
                + ": "
                + csv);
      }
    }
    return values;
  }
}
